language: generic
sudo: required
services:
    - docker
before install:
    - docker build -t laportetyler/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true laportetyler/react-test npm test

after_sucess:
    - docker build -t laportetyler/multi-client ./client
    - docker build -t laportetyler/multi-nginx ./nginx
    - docker build -t laportetyler/multi-server ./server
    - docker build -t laportetyler/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push to docker hub
    - docker push laportetyler/multi-client
    - docker push laportetyler/multi-nginx
    - docker push laportetyler/multi-server
    - docker push laportetyler/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-2-539682570970"
    bucket_path: "multi-docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY